/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as CitizenChatbotRouteImport } from './routes/citizen.chatbot'
import { Route as CitizenComplaintsRouteImport } from './routes/citizen.complaints'
import { Route as CitizenContactsRouteImport } from './routes/citizen.contacts'
import { Route as CitizenHomeRouteImport } from './routes/citizen.home'
import { Route as CitizenLoginRouteImport } from './routes/citizen.login'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenRulebookRouteImport } from './routes/citizen.rulebook'
import { Route as CitizenServicesRouteImport } from './routes/citizen.services'
import { Route as CitizenSignupRouteImport } from './routes/citizen.signup'
import { Route as AdminComplaintsIndexRouteImport } from './routes/admin.complaints.index'
import { Route as AdminComplaintsIdRouteImport } from './routes/admin.complaints.$id'
import { Route as CitizenComplaintNewRouteImport } from './routes/citizen.complaint.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenChatbotRoute = CitizenChatbotRouteImport.update({
  id: '/citizen/chatbot',
  path: '/citizen/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenComplaintsRoute = CitizenComplaintsRouteImport.update({
  id: '/citizen/complaints',
  path: '/citizen/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenContactsRoute = CitizenContactsRouteImport.update({
  id: '/citizen/contacts',
  path: '/citizen/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenHomeRoute = CitizenHomeRouteImport.update({
  id: '/citizen/home',
  path: '/citizen/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenLoginRoute = CitizenLoginRouteImport.update({
  id: '/citizen/login',
  path: '/citizen/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/citizen/profile',
  path: '/citizen/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRulebookRoute = CitizenRulebookRouteImport.update({
  id: '/citizen/rulebook',
  path: '/citizen/rulebook',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenServicesRoute = CitizenServicesRouteImport.update({
  id: '/citizen/services',
  path: '/citizen/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenSignupRoute = CitizenSignupRouteImport.update({
  id: '/citizen/signup',
  path: '/citizen/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/admin/complaints/',
  path: '/admin/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsIdRoute = AdminComplaintsIdRouteImport.update({
  id: '/admin/complaints/$id',
  path: '/admin/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenComplaintNewRoute = CitizenComplaintNewRouteImport.update({
  id: '/citizen/complaint/new',
  path: '/citizen/complaint/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/rules': typeof AdminRulesRoute
  '/citizen/chatbot': typeof CitizenChatbotRoute
  '/citizen/complaints': typeof CitizenComplaintsRoute
  '/citizen/contacts': typeof CitizenContactsRoute
  '/citizen/home': typeof CitizenHomeRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/rulebook': typeof CitizenRulebookRoute
  '/citizen/services': typeof CitizenServicesRoute
  '/citizen/signup': typeof CitizenSignupRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/citizen/complaint/new': typeof CitizenComplaintNewRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/rules': typeof AdminRulesRoute
  '/citizen/chatbot': typeof CitizenChatbotRoute
  '/citizen/complaints': typeof CitizenComplaintsRoute
  '/citizen/contacts': typeof CitizenContactsRoute
  '/citizen/home': typeof CitizenHomeRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/rulebook': typeof CitizenRulebookRoute
  '/citizen/services': typeof CitizenServicesRoute
  '/citizen/signup': typeof CitizenSignupRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/citizen/complaint/new': typeof CitizenComplaintNewRoute
  '/admin/complaints': typeof AdminComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/rules': typeof AdminRulesRoute
  '/citizen/chatbot': typeof CitizenChatbotRoute
  '/citizen/complaints': typeof CitizenComplaintsRoute
  '/citizen/contacts': typeof CitizenContactsRoute
  '/citizen/home': typeof CitizenHomeRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/rulebook': typeof CitizenRulebookRoute
  '/citizen/services': typeof CitizenServicesRoute
  '/citizen/signup': typeof CitizenSignupRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/citizen/complaint/new': typeof CitizenComplaintNewRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/announcements'
    | '/admin/forgot-password'
    | '/admin/home'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/rules'
    | '/citizen/chatbot'
    | '/citizen/complaints'
    | '/citizen/contacts'
    | '/citizen/home'
    | '/citizen/login'
    | '/citizen/profile'
    | '/citizen/rulebook'
    | '/citizen/services'
    | '/citizen/signup'
    | '/admin/complaints/$id'
    | '/citizen/complaint/new'
    | '/admin/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/announcements'
    | '/admin/forgot-password'
    | '/admin/home'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/rules'
    | '/citizen/chatbot'
    | '/citizen/complaints'
    | '/citizen/contacts'
    | '/citizen/home'
    | '/citizen/login'
    | '/citizen/profile'
    | '/citizen/rulebook'
    | '/citizen/services'
    | '/citizen/signup'
    | '/admin/complaints/$id'
    | '/citizen/complaint/new'
    | '/admin/complaints'
  id:
    | '__root__'
    | '/'
    | '/admin/announcements'
    | '/admin/forgot-password'
    | '/admin/home'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/rules'
    | '/citizen/chatbot'
    | '/citizen/complaints'
    | '/citizen/contacts'
    | '/citizen/home'
    | '/citizen/login'
    | '/citizen/profile'
    | '/citizen/rulebook'
    | '/citizen/services'
    | '/citizen/signup'
    | '/admin/complaints/$id'
    | '/citizen/complaint/new'
    | '/admin/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminRulesRoute: typeof AdminRulesRoute
  CitizenChatbotRoute: typeof CitizenChatbotRoute
  CitizenComplaintsRoute: typeof CitizenComplaintsRoute
  CitizenContactsRoute: typeof CitizenContactsRoute
  CitizenHomeRoute: typeof CitizenHomeRoute
  CitizenLoginRoute: typeof CitizenLoginRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenRulebookRoute: typeof CitizenRulebookRoute
  CitizenServicesRoute: typeof CitizenServicesRoute
  CitizenSignupRoute: typeof CitizenSignupRoute
  AdminComplaintsIdRoute: typeof AdminComplaintsIdRoute
  CitizenComplaintNewRoute: typeof CitizenComplaintNewRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/admin/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/chatbot': {
      id: '/citizen/chatbot'
      path: '/citizen/chatbot'
      fullPath: '/citizen/chatbot'
      preLoaderRoute: typeof CitizenChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/complaints': {
      id: '/citizen/complaints'
      path: '/citizen/complaints'
      fullPath: '/citizen/complaints'
      preLoaderRoute: typeof CitizenComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/contacts': {
      id: '/citizen/contacts'
      path: '/citizen/contacts'
      fullPath: '/citizen/contacts'
      preLoaderRoute: typeof CitizenContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/home': {
      id: '/citizen/home'
      path: '/citizen/home'
      fullPath: '/citizen/home'
      preLoaderRoute: typeof CitizenHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/login': {
      id: '/citizen/login'
      path: '/citizen/login'
      fullPath: '/citizen/login'
      preLoaderRoute: typeof CitizenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/citizen/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/rulebook': {
      id: '/citizen/rulebook'
      path: '/citizen/rulebook'
      fullPath: '/citizen/rulebook'
      preLoaderRoute: typeof CitizenRulebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/services': {
      id: '/citizen/services'
      path: '/citizen/services'
      fullPath: '/citizen/services'
      preLoaderRoute: typeof CitizenServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/signup': {
      id: '/citizen/signup'
      path: '/citizen/signup'
      fullPath: '/citizen/signup'
      preLoaderRoute: typeof CitizenSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/': {
      id: '/admin/complaints/'
      path: '/admin/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/$id': {
      id: '/admin/complaints/$id'
      path: '/admin/complaints/$id'
      fullPath: '/admin/complaints/$id'
      preLoaderRoute: typeof AdminComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/complaint/new': {
      id: '/citizen/complaint/new'
      path: '/citizen/complaint/new'
      fullPath: '/citizen/complaint/new'
      preLoaderRoute: typeof CitizenComplaintNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminRulesRoute: AdminRulesRoute,
  CitizenChatbotRoute: CitizenChatbotRoute,
  CitizenComplaintsRoute: CitizenComplaintsRoute,
  CitizenContactsRoute: CitizenContactsRoute,
  CitizenHomeRoute: CitizenHomeRoute,
  CitizenLoginRoute: CitizenLoginRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenRulebookRoute: CitizenRulebookRoute,
  CitizenServicesRoute: CitizenServicesRoute,
  CitizenSignupRoute: CitizenSignupRoute,
  AdminComplaintsIdRoute: AdminComplaintsIdRoute,
  CitizenComplaintNewRoute: CitizenComplaintNewRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
